"""update order and order item table

Revision ID: 7fef6e4d37d8
Revises: b97d0c6a8ad1
Create Date: 2025-11-07 23:58:59.288864

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7fef6e4d37d8"
down_revision = "b97d0c6a8ad1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customer",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "customer",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.drop_index(op.f("ix_product_sku"), table_name="product")
    op.create_unique_constraint(None, "product", ["sku"])
    op.alter_column(
        "sales_order",
        "payment_method",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        server_default=sa.text("'cash'::character varying"),
    )
    op.alter_column(
        "sales_order",
        "confirmed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "sales_order",
        "paid_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "sales_order",
        "fulfilled_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "sales_order",
        "cancelled_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "sales_order",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "sales_order",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.drop_index(op.f("ix_sales_order_assigned_to"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_created_at"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_customer_id"), table_name="sales_order")
    op.drop_index(op.f("ix_sales_order_status"), table_name="sales_order")
    op.drop_constraint(
        op.f("sales_order_order_number_key"), "sales_order", type_="unique"
    )
    op.create_index(
        op.f("ix_sales_order_order_number"),
        "sales_order",
        ["order_number"],
        unique=True,
    )
    op.drop_constraint(
        op.f("sales_order_assigned_to_fkey"), "sales_order", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("sales_order_customer_id_fkey"), "sales_order", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("sales_order_customer_id_fkey"),
        "sales_order",
        "customer",
        ["customer_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("sales_order_assigned_to_fkey"),
        "sales_order",
        "user",
        ["assigned_to"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_sales_order_order_number"), table_name="sales_order")
    op.create_unique_constraint(
        op.f("sales_order_order_number_key"),
        "sales_order",
        ["order_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_sales_order_status"), "sales_order", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_customer_id"), "sales_order", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_created_at"), "sales_order", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_assigned_to"), "sales_order", ["assigned_to"], unique=False
    )
    op.alter_column(
        "sales_order",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "sales_order",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "sales_order",
        "cancelled_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "sales_order",
        "fulfilled_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "sales_order",
        "paid_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "sales_order",
        "confirmed_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "sales_order",
        "status",
        existing_type=order_status_enum,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'draft'::character varying"),
    )
    op.alter_column(
        "sales_order",
        "payment_status",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        server_default=sa.text("'unpaid'::character varying"),
    )
    op.alter_column(
        "sales_order",
        "payment_method",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        server_default=sa.text("'cod'::character varying"),
    )
    op.drop_constraint(None, "product", type_="unique")
    op.create_index(op.f("ix_product_sku"), "product", ["sku"], unique=True)
    op.alter_column(
        "customer",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "customer",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    # ### end Alembic commands ###
