"""create table customer

Revision ID: 8ebfbe431741
Revises: ea98203c92ce
Create Date: 2025-11-07 18:09:09.975758

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "8ebfbe431741"
down_revision = "ea98203c92ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_email"), "customer", ["email"], unique=False)
    op.create_index(op.f("ix_customer_phone"), "customer", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customer_phone"), table_name="customer")
    op.drop_index(op.f("ix_customer_email"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
